name: Publish

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine check-manifest
      - name: Check MANIFEST.in
        run: check-manifest
      - name: Build package
        run: python -m build
      - name: Twine check
        run: twine check dist/*
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          if-no-files-found: error
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
